### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Invalid index 86, size is 57

### ISSUE THREAD

**Issue by ccnn** [AigeStudio/WheelPicker#28]
IndexOutOfBounds after setYearRange, But it's not always happen;
ExceptionStackMsg:
java.lang.IndexOutOfBoundsException: Invalid index 86, size is 57
	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
	at java.util.ArrayList.get(ArrayList.java:308)
	at com.aigestudio.wheelpicker.core.AbstractWheelPicker.onSizeChanged(AbstractWheelPicker.java:234)
	at com.aigestudio.wheelpicker.view.WheelCrossPicker.onSizeChanged(WheelCrossPicker.java:69)
	at android.view.View.sizeChange(View.java:16135)

**Comment by AigeStudio** [comment]
You can try WheelPicker 1.1.0
